name: Lint Codebase

on:
  workflow_call:

permissions: {}

jobs:
  other-linter:
    name: Lint Others
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: setup aqua
        uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
        with:
          aqua_version: v2.28.0
          aqua_opts: ""

      - name: Lint GitHub Action
        run: |
          ghalint run-action

      - name: Lint GitHub Actions workflows
        run: |
          ghalint run

  super-linter:
    name: Lint Codebase
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: read
      statuses: write
      pull-requests: write
      issues: write


    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: load env for super-linter
        run: |
          grep -v '#' superlinter.env >> "$GITHUB_ENV"
        working-directory: ${{ github.workspace }}/.github/linters

      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@9e863354e3ff62e0727d37183162c4a88873df41 # v8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
