name: Lint Codebase

on:
  workflow_call:

permissions: {}

jobs:
  super-linter:
    name: Lint Codebase
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: read
      statuses: write
      pull-requests: write
      issues: write


    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: load env for super-linter
        run: |
          grep -v '#' superlinter.env >> "$GITHUB_ENV"
        working-directory: ${{ github.workspace }}/.github/linters

      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          SAVE_SUPER_LINTER_SUMMARY: true
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: false

      - name: Update sticky PR comment
        if: always() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          header: super-linter-report
          path: ${{ github.workspace }}/super-linter-output/super-linter-summary.md
