on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

permissions: {}

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml
    with:
      gh_app_release_client_id: ${{ vars.GH_APP_RELEASE_CLIENT_ID }}
    secrets:
      GH_APP_RELEASE_PRIVATE_KEY: ${{ secrets.GH_APP_RELEASE_PRIVATE_KEY }}
    permissions:
      actions: read
      checks: write
      contents: write
      packages: read
      security-events: write
      statuses: write
      issues: write
      pull-requests: write
  
  check-result:
    needs: ci
    runs-on: ubuntu-slim
    timeout-minutes: 5
    if: ${{ always() && needs.ci.result != 'success' }}
    steps:
      - name: exit with failure
        run: exit 1
