name: Release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    timeout-minutes: 10
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.GH_APP_RELEASE_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_RELEASE_PRIVATE_KEY }}
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        id: release-please
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

      - name: get app information
        id: app-info
        run: |
          echo "app-user-id=$(gh api "/users/${APP_SLUG}[bot]" --jq .id)" >> "${GITHUB_OUTPUT}"
          echo "APP_SLUG=${APP_SLUG}" >> "${GITHUB_ENV}"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: config git
        run: |
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        env:
          GIT_USER_NAME: "${{ env.APP_SLUG }}[bot]"
          GIT_USER_EMAIL: "${{ steps.app-info.outputs.app-user-id }}+${{ env.APP_SLUG }}[bot]@users.noreply.github.com"
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      # https://github.com/googleapis/release-please-action?tab=readme-ov-file#creating-majorminor-tags
      - name: update major and minor tags
        if: steps.release-please.outputs.release_created == 'true'
        run: |
          git tag -d "v${MAJOR_VERSION}" || true
          git tag -d "v${MAJOR_VERSION}.${MINOR_VERSION}" || true
          git push --delete origin "v${MAJOR_VERSION}" || true
          git push --delete origin "v${MAJOR_VERSION}.${MINOR_VERSION}" || true

          git fetch --tags
          git tag -a "v${MAJOR_VERSION}" -m "Release v${MAJOR_VERSION}"
          git tag -a "v${MAJOR_VERSION}.${MINOR_VERSION}" -m "Release v${MAJOR_VERSION}.${MINOR_VERSION}"
          git push origin --tags
        env:
          MAJOR_VERSION: ${{ steps.release-please.outputs.major }}
          MINOR_VERSION: ${{ steps.release-please.outputs.minor }}
